spring:
   config:
      import: optional:file:.env[.properties]
   profiles:
      active: ${SPRING_PROFILES_ACTIVE}

springdoc:
   default-produces-media-type: application/json
server:
   servlet:
      context-path: /api/v1/

